format_version: v1.0
type: UniqueComponent
attributes: {id: rtc}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: RTC_CLOCK_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: SECURE}
  - type: File
    attributes: {id: RTC_INSTANCE_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: SECURE}
  - type: Hex
    attributes: {id: RTC_MODE0_EVCTRL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rtc, value: '32'}
  - type: Boolean
    attributes: {id: RTC_MODE0_EVCTRL_PEREO5_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: RTC_SYS_DEF}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_DEFINITIONS_SECURE_H_INCLUDES}
  - type: File
    attributes: {id: RTC_SYS_INIT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: core.LIST_SYSTEM_SECURE_INIT_C_SYS_INITIALIZE_PERIPHERALS}
  - type: File
    attributes: {id: RTC_TIMER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: security}
        children:
        - {type: Value, value: SECURE}
- type: ElementPosition
  attributes: {x: '55', y: '134', id: rtc}
