configName: sam_l10_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAML10E16A
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;core_apps_pic32cm_mc00;core_apps_pic32mx;core_apps_pic32mz_w1;core_apps_sam_c20_c21;core_apps_sam_d20;core_apps_sam_d21_da1;core_apps_sam_d5x_e5x;core_apps_sam_l10_l11;core_apps_sam_l21;core_apps_sam_l22;crypto;cryptoauthlib;cryptoauthlib_apps;csp;csp_apps_pic32cm_mc00;csp_apps_pic32mk;csp_apps_pic32mx;csp_apps_pic32mz_w1;csp_apps_sam_c20_c21;csp_apps_sam_d20;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_l10_l11;csp_apps_sam_l21;csp_apps_sam_l22;gfx;micrium_ucos3;net;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAML10_DFP\3.3.79\atdf\ATSAML10E16A.atdf
