format_version: v1.0
type: UniqueComponent
attributes: {id: tc2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '32000000'}
  - type: Long
    attributes: {id: TC_TIMER_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: '319'}
  - type: Float
    attributes: {id: TC_TIMER_TIME_MS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0.01'}
- type: ElementPosition
  attributes: {x: '489', y: '100', id: tc2}
