format_version: v1.0
type: UniqueComponent
attributes: {id: opamp}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: OPAMP_OPAMPCTRL_2_ANAOUT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: OPAMP_OPAMPCTRL_2_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: OPAMP_OPAMPCTRL_2_MUXNEG}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: OPAMP_OPAMPCTRL_2_POTMUX}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: OPAMP_OPAMPCTRL_2_RES1EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: OPAMP_OPAMPCTRL_2_RES1MUX}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Boolean
    attributes: {id: OPAMP_OPAMPCTRL_2_RES2OUT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: OPAMP_OPAMPCTRL_2_RES2VCC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '490', y: '243', id: opamp}
