format_version: v1.0
type: UniqueComponent
attributes: {id: freqm}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: FREQM_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: FREQM_REF_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: freqm, value: '32768'}
  - type: Comment
    attributes: {id: FREQM_REF_CLOCK_FREQUENCY_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** Reference Clock Frequency 32768.0 Hz ***'}
  - type: Integer
    attributes: {id: FREQM_RESULT_RIGHT_SHIFT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: freqm, value: '0'}
  - type: Comment
    attributes: {id: FREQ_MEASUREMENT_TIME_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** Measurement Time 0.031 mS ***'}
- type: ElementPosition
  attributes: {x: '270', y: '120', id: freqm}
